"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = 'clarity'
format = """
[┍━](frame)$time$username$hostname$directory$git_branch$git_state$git_status$python$container$jobs$cmd_duration$status
$character"""

[character]
success_symbol = '[┕━](frame) [≡](bold accent)[::{{](frame)[\$](bold usd)[}::{](frame)[€](bold eur)[}::{](frame)[¥](bold jpy)[}}::](frame)[≡](bold accent)'
error_symbol   = '[┕━ ≡::{{\$}::{€}::{¥}}::⊥](bold warn)'
vimcmd_symbol  = '[┕━ ≡::{{\$}::{€}::{¥}}::≡](bold mode)'

[time]
disabled = false
time_format = '%T'
format = '[$time]($style) '
style = 'dim'

[username]
show_always = true
format = '[$user]($style)@'
style_user = 'text'
style_root = 'bold warn'

[hostname]
ssh_only = false
ssh_symbol = 'ssh:'
format = '[$ssh_symbol$hostname]($style):'
style = 'text'

[directory]
truncation_length = 3
read_only = ' ro'
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold accent'
read_only_style = 'warn'

[git_branch]
style = 'dim'

[git_status]
style = 'mode'

[python]
style = 'usd'

[container]
style = 'dim'

[jobs]
style = 'accent'

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style) '
style = 'dim'

[status]
disabled = false
format = '[::{$status}::]($style) '
style = 'bold warn'

[palettes.clarity]
frame  = '5'    # #696ebf  purple
dim    = '8'    # #4a697d  slate
text   = '7'    # #bfbaac  stone
accent = '13'   # #8086e8  bright purple
usd    = '11'   # #d9a400  gold
eur    = '12'   # #AFDDFF  ice
jpy    = '15'   # #fdf6e3  ivory
warn   = '1'    # #EE615C  red
mode   = '14'   # #33c5ba  cyan
