#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width		 16
bspc config window_gap           32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#289c93'
bspc config active_border_color '#8086e8'
bspc config focused_border_color '#696ebf' 
